version: '3'
services:
  loki:
    image: grafana/loki:latest
    hostname: loki
    volumes:
      - loki_data:/loki
      - ./loki/loki-docker-config.yml:/etc/loki/loki-docker-config.yml
    command: 
      - '--config.file=/etc/loki/loki-docker-config.yml'
    ports:
      - '3100:3100'
    restart: always
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - loki
    ports:
      - '3000:3000'
    restart: always
  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   ports:
  #     - '8080:8080'
  #   command: 'index.js'
  #   restart: always

volumes:
  loki_data: {}
  grafana_data: {}
