{
 "title": "reportid-sample",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "reportid", "query": "114514" }
  ]
 },
 "panels": [
  {
   "title": "页面关键性能 pagePerformance",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pagePerformance{job=\"$reportid\",type=\"FP\"}",
     "legendFormat": "FP"
    },
    {
     "expr": "pagePerformance{job=\"$reportid\",type=\"FCP\"}",
     "legendFormat": "FCP"
    },
    {
     "expr": "pagePerformance{job=\"$reportid\",type=\"DNS\"}",
     "legendFormat": "DNS"
    },
    {
     "expr": "pagePerformance{job=\"$reportid\",type=\"DOMready\"}",
     "legendFormat": "DOMready"
    },
    {
     "expr": "pagePerformance{job=\"$reportid\",type=\"TCPduration\"}",
     "legendFormat": "TCPduration"
    },
    {
     "expr": "pagePerformance{job=\"$reportid\",type=\"requestTime\"}",
     "legendFormat": "requestTime"
    }
   ]
  },
  {
   "title": "页面停留时间 pageStay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pageStay{job=\"114514\"}",
     "legendFormat": "{{pageurl}}"
    }
   ]
  },
  {
   "title": "白屏错误监测 blankScreenError",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "blankScreenError{job=\"114514\"}",
     "legendFormat": "{{pageurl}}"
    }
   ]
  }
 ]
}