{
 "title": "reportid-114514",
 "time": { "from": "2022-08-08T18:28:00.873Z", "to": "2022-08-08T19:24:14.771Z" },
 "panels": [
  {
   "title": "页面关键性能 pagePerformance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "时间 (ms)" }
   ],
   "targets": [
    {
     "expr": "pagePerformance{job=\"114514\",type=\"FP\"}",
     "legendFormat": "FP"
    },
    {
     "expr": "pagePerformance{job=\"114514\",type=\"FCP\"}",
     "legendFormat": "FCP"
    },
    {
     "expr": "pagePerformance{job=\"114514\",type=\"DNS\"}",
     "legendFormat": "DNS"
    },
    {
     "expr": "pagePerformance{job=\"114514\",type=\"DOMready\"}",
     "legendFormat": "DOMready"
    },
    {
     "expr": "pagePerformance{job=\"114514\",type=\"TCPduration\"}",
     "legendFormat": "TCPduration"
    },
    {
     "expr": "pagePerformance{job=\"114514\",type=\"requestTime\"}",
     "legendFormat": "requestTime"
    }
   ]
  },
  {
   "title": "页面停留时间 pageStay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "时间 (ms)" }
   ],
   "targets": [
    {
     "expr": "pageStay{job=\"114514\"}",
     "legendFormat": "{{pageurl}}"
    }
   ]
  },
  {
   "title": "白屏错误监测 blankScreenError",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "包裹元素的数量" }
   ],
   "targets": [
    {
     "expr": "blankScreenError{job=\"114514\"}",
     "legendFormat": "{{pageurl}}"
    }
   ]
  }
 ]
}